version: '3'
services:
  moe-counter:
    image: "registry.cn-shanghai.aliyuncs.com/iproute/getloli"
    container_name: "getloli"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./data:/app/data"
    environment:
      - TZ=Asia/Shanghai